- name: Check if kafka service is running
  shell: ps aux | grep kafka | grep -v grep
  ignore_errors: yes
  register: kafka_service_status

- name: Kafka process check output
  debug:
    msg: "{{ kafka_service_status.rc }}"

- name: Kafka process check output
  debug:
    msg: "{{ kafka_service_status }}"

- name: Kafka sevice (running or stopped) report
  debug:
    msg: "Kafka server is {% if kafka_service_status.rc != 0 %}not {% endif %}running"

- name: Kafka start {{ KAFKA_HOME }}/bin"
  become: yes
  become_user: centos
  shell: "{{ KAFKA_START_COMMAND }}"
  args:
    chdir: "{{ KAFKA_HOME }}/bin"
  when: kafka_service_status.rc != 0
