KAFKA_VERSION: 0.10.1.1
KAFKA_SCALA_VERSION: "2.11"
KAFKA_URL: "https://archive.apache.org/dist//kafka/{{ KAFKA_VERSION }}/kafka_{{ KAFKA_SCALA_VERSION }}-{{ KAFKA_VERSION }}.tgz"
KAFKA_TAR: kafka_{{ KAFKA_SCALA_VERSION }}-{{ KAFKA_VERSION }}.tgz
KAFKA_SOURCE_FOLDER: kafka_{{ KAFKA_SCALA_VERSION }}-{{ KAFKA_VERSION }}
INSTALLATION_DIR: /usr/local
KAFKA_HOME: "{{ INSTALLATION_DIR }}/kafka"
KAFKA_LOG_DIR: /var/log/kafka

# Kafka service commands
KAFKA_STOP_COMMAND: "./kafka-server-stop.sh; sleep 20"
KAFKA_START_COMMAND: "nohup ./kafka-server-start.sh -daemon ../config/server.properties &"
KAFKA_USER: "centos"
# Unix user and group
UNIX_KAFKA_USER: centos
UNIX_KAFKA_GROUP: centos

JMX_ENABLED: true
JMX_PORT: 9999
