pipeline {
    agent any

    environment {
        TF_IN_AUTOMATION      = '1'
        PATH = "/usr/local/bin:$PATH"
    }

    stages {


        stage('Plan') {
            steps {
                script {
                    currentBuild.displayName = params.version
                }
                

                dir('./kafka/'){
                    sh '/usr/local/bin/aws s3 cp s3://terraform-examples-series/kafka/terraform.pem . && chmod 400 terraform.pem'
                    sh "terraform init && terraform plan -input=false -out tfplan -var CLUSTER_SIZE=${cluster_size} -var CLUSTER_NAME=${cluster_name} --var-file=environments/${params.environment}/variable.tfvars"
                    sh 'terraform show -no-color tfplan > tfplan.txt'
                }
            }
        }

        stage('Approval') {
            when {
                not {
                    equals expected: true, actual: params.autoApprove
                }
            }

            steps {
                script {
                    def plan = readFile './kafka/tfplan.txt'
                    input message: "Do you want to apply the plan?",
                        parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
                }
            }
        }

        stage('Apply') {
            steps {
                dir('./kafka/'){
                    sh "terraform apply -input=false tfplan"
                }
            }
        }

        stage('PostInstall') {
            steps {
                dir('./kafka/'){
                    sh "/usr/local/bin/aws s3 cp terraform* tfplan s3://terraform-examples-series/kafka-backup/${cluster_name}/"
                }
            }
        }


    }

    post {
        always {
            archiveArtifacts artifacts: 'kafka/tfplan.txt'
	    cleanWs()
        }
    }
}
